version: "3"
services:
  web:
    image: nginx:alpine
    hostname: ${WEB_HOSTNAME}
    volumes:
      - ${CONFIGURATION_ROOT}/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PROJECT_ROOT}:/var/www/html:ro
      - typo3tempRamdisk:/var/www/html/Web/typo3temp:ro
      - typo3varRamdisk:/var/www/html/var:ro
    expose: [80]
    depends_on:
      - db
      - php

  db:
    image: mariadb
    env_file:
      - ./.env
    volumes:
      - ${CONFIGURATION_ROOT}/db:/docker-entrypoint-initdb.d/:ro
      - ${CONFIGURATION_ROOT}/db/mysql.cnf:/etc/mysql/zzz-custom.cnf:ro
      - dbRamdisk:/var/lib/mysql

  php:
    build: ${CONFIGURATION_ROOT}/php/
    volumes:
      - ${CONFIGURATION_ROOT}/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ${CONFIGURATION_ROOT}/php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ${PROJECT_ROOT}:/var/www/html
      - typo3tempRamdisk:/var/www/html/Web/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - before_script

  before_script:
    image: busybox:latest
    volumes:
      - ${PROJECT_ROOT}:/build
      - ${CONFIGURATION_ROOT}:/configuration
    entrypoint: /configuration/before_script/init.sh

  mailhog:
    image: mailhog/mailhog
    expose: [8025]

  hostmap:
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/hosts:/tmp/hosts

volumes:
  dbRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: noatime,noexec,nodiratime,nodev,nosuid,async,mode=0777
  typo3tempRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: noatime,noexec,nodiratime,nodev,nosuid,async,mode=0777
  typo3varRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: noatime,noexec,nodiratime,nodev,nosuid,async,mode=0777
