version: "3"
services:
  web:
    image: fholzer/nginx-brotli
    container_name: ${COMPOSE_PROJECT_NAME}_web
    hostname: ${COMPOSE_PROJECT_NAME}.dev.local
    volumes:
      - ${HOSTS_FILE:-/etc/hosts}:/etc/hosts:ro
      - ./global/group:/etc/group:ro
      - ./global/group-:/etc/group-:ro
      - ./global/passwd:/etc/passwd:ro
      - ./global/passwd-:/etc/passwd-:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/ssl:/etc/nginx/ssl:ro
      - $PWD:/var/www/html:ro
      - typo3tempRamdisk:/var/www/html/public/typo3temp:ro
      - typo3varRamdisk:/var/www/html/var:ro
      # Apache settings
#      - ./web/httpd.2.4.conf:/usr/local/apache2/conf/httpd.conf:ro
#      - ./web/httpd.2.4.vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
#      - ./web/ssl/private.rsa:/usr/local/apache2/conf/private.rsa:ro
#      - ./web/ssl/public.crt:/usr/local/apache2/conf/public.crt:ro
#      - ./web/ca/cacert.crt:/usr/local/apache2/conf/cacert.crt:ro
    networks:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.bf.local
          - ${COMPOSE_PROJECT_NAME}.black.local
          - ${COMPOSE_PROJECT_NAME}.blackfire.local
          - ${COMPOSE_PROJECT_NAME}.debug.local
          - ${COMPOSE_PROJECT_NAME}.fire.local
          - ${COMPOSE_PROJECT_NAME}.logs.local
          - ${COMPOSE_PROJECT_NAME}.mail.local
          - ${COMPOSE_PROJECT_NAME}.xdbg.local
          - ${COMPOSE_PROJECT_NAME}.xdebug.local
    depends_on:
      - before_script
      - db
      - php
      - php_blackfire
      - php_xdebug

  db:
    image: mariadb
    hostname: ${COMPOSE_PROJECT_NAME}_db
    container_name: ${COMPOSE_PROJECT_NAME}_db
    env_file:
      - $PWD/.env
    volumes:
      #- dbRamdisk:/var/lib/mysql
      - $PWD/.docker/db/mysql:/var/lib/mysql
      - ./db/mariadb.cnf:/etc/mysql/conf.d/zz-my-mariadb.cnf:ro
      - ./db/mariadb.cnf:/etc/mysql/mysql.d/zz-my-mariadb.cnf:ro
      - ./db/import:/docker-entrypoint-initdb.d/:ro
    depends_on:
      - before_script

  php:
    image: tuurlijk/php-fpm:7.4
    hostname: ${COMPOSE_PROJECT_NAME}_php
    container_name: ${COMPOSE_PROJECT_NAME}_php
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
    volumes:
      - $PWD/:/var/www/html/
      - ${HOSTS_FILE:-/etc/hosts}:/etc/hosts:ro
      - ./global/group:/etc/group:ro
      - ./global/group-:/etc/group-:ro
      - ./global/passwd:/etc/passwd:ro
      - ./global/passwd-:/etc/passwd-:ro
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - typo3tempRamdisk:/var/www/html/public/typo3temp
      - typo3varRamdisk:/var/www/html/var
      - ${HOME:-~}/.composer:/home/dev/.composer
      - ${HOME:-~}/.composer:/home/docker/.composer
    depends_on:
      - before_script

  php_blackfire:
    image: tuurlijk/php-fpm:7.4-blackfire
    hostname: ${COMPOSE_PROJECT_NAME}_php_blackfire
    container_name: ${COMPOSE_PROJECT_NAME}_php_blackfire
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
    volumes:
      - $PWD/:/var/www/html/
      - ${HOSTS_FILE:-/etc/hosts}:/etc/hosts:ro
      - ./global/group:/etc/group:ro
      - ./global/group-:/etc/group-:ro
      - ./global/passwd:/etc/passwd:ro
      - ./global/passwd-:/etc/passwd-:ro
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ./php_blackfire/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - typo3tempRamdisk:/var/www/html/public/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - before_script

  php_xdebug:
    image: tuurlijk/php-fpm:7.4-xdebug
    hostname: ${COMPOSE_PROJECT_NAME}_php_xdebug
    container_name: ${COMPOSE_PROJECT_NAME}_php_xdebug
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
      - PHP_IDE_CONFIG=serverName=${COMPOSE_PROJECT_NAME}
    volumes:
      - $PWD/:/var/www/html/
      - ./global/group:/etc/group:ro
      - ./global/group-:/etc/group-:ro
      - ./global/passwd:/etc/passwd:ro
      - ./global/passwd-:/etc/passwd-:ro
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ./php_xdebug/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - typo3tempRamdisk:/var/www/html/public/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - before_script
    extra_hosts:
      - "host.docker.internal:host-gateway"

  blackfire:
    image: blackfire/blackfire
    container_name: ${COMPOSE_PROJECT_NAME}_blackfire
    environment:
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID:-id}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN:-token}
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID:-id}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN:-token}
    depends_on:
      - php_blackfire
      - web

  before_script:
    user: "${UID:-1000}:${GID:-1000}"
    image: bash
    container_name: ${COMPOSE_PROJECT_NAME}_before_script
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
    volumes:
      - $PWD:/build
      - ./:/configuration
    entrypoint: /configuration/template/${TEMPLATE:-default}/before.sh
    depends_on:
      - before

  after_script:
    user: "${UID:-1000}:${GID:-1000}"
    image: tuurlijk/php-fpm:7.4
    container_name: ${COMPOSE_PROJECT_NAME}_after_script
    env_file:
      - $PWD/.env
    volumes:
      - ./:/configuration
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - $PWD:/var/www/html
      - ${HOME:-~}/.composer:/home/dev/.composer
      - ${HOME:-~}/.composer:/home/docker/.composer
      - typo3tempRamdisk:/var/www/html/public/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - web
    entrypoint: /configuration/template/${TEMPLATE:-default}/after.sh

  mailhog:
    image: mailhog/mailhog
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    depends_on:
      - before_script

#  ngrok:
#    image: wernight/ngrok
#    container_name: ${COMPOSE_PROJECT_NAME}_ngrok
#    environment:
#      - NGROK_AUTH=${NGROK_AUTH:-nan}
#      - NGROK_PORT=${NGROK_PORT:-nan}
#      - NGROK_REGION=${NGROK_REGION:-eu}
#      - NGROK_BINDTLS=${NGROK_BINDTLS:-true}
#      - NGROK_USERNAME=${NGROK_USERNAME:-nan}
#      - NGROK_PASSWORD=${NGROK_PASSWORD:-}
#    depends_on:
#      - web

  hosts:
    image: ${HOSTS_IMAGE:-dvdarias/docker-hoster}
    container_name: ${COMPOSE_PROJECT_NAME}_hosts
    volumes:
      - //var/run/docker.sock:/tmp/docker.sock:ro
      - ${HOSTS_FILE:-/etc/hosts}:/tmp/hosts

  logs:
    image: amir20/dozzle
    container_name: ${COMPOSE_PROJECT_NAME}_logs
    environment:
      - DOZZLE_FILTER=name=${COMPOSE_PROJECT_NAME}_(web|php*|db|mail*|solr|redis)_*
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock:ro

  before:
    user: "${UID:-1000}:${GID:-1000}"
    image: bash
    container_name: ${COMPOSE_PROJECT_NAME}_before
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
    volumes:
      - $PWD/:/build
      - ./:/configuration
      - ./global/group:/etc/group
      - ./global/group-:/etc/group-
      - ./global/passwd:/etc/passwd
      - ./global/passwd-:/etc/passwd-
    entrypoint: /configuration/before/before.sh

#  redis:
#    image: redis
#    container_name: ${COMPOSE_PROJECT_NAME}_redis

#  chrome:
#    image: robcherry/docker-chromedriver
#    hostname: ${COMPOSE_PROJECT_NAME}_chrome
#    container_name: ${COMPOSE_PROJECT_NAME}_chrome
#    environment:
#       CHROMEDRIVER_WHITELISTED_IPS: ""
#       CHROMEDRIVER_PORT: "9515"
#    ports:
#       - 9515:9515
#    cap_add:
#       - "SYS_ADMIN"

volumes:
  dbRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "noatime,noexec,nodiratime,nodev,nosuid,async,mode=0770,uid=${UID:-1000},gid=${GID:-1000}"
  typo3tempRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "noatime,noexec,nodiratime,nodev,nosuid,async,mode=0770,uid=${UID:-1000},gid=${GID:-1000}"
  typo3varRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "noatime,noexec,nodiratime,nodev,nosuid,async,mode=0770,uid=${UID:-1000},gid=${GID:-1000}"
