version: "3"
services:
  web:
    image: fholzer/nginx-brotli
    hostname: ${WEB_HOSTNAME}
    volumes:
      - ${CONFIGURATION_ROOT}/web/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${CONFIGURATION_ROOT}/web/ssl:/etc/nginx/ssl:ro
      - ${PROJECT_ROOT}:/var/www/html:ro
      - typo3tempRamdisk:/var/www/html/Web/typo3temp:ro
      - typo3varRamdisk:/var/www/html/var:ro
    networks:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.bf.local
          - ${COMPOSE_PROJECT_NAME}.black.local
          - ${COMPOSE_PROJECT_NAME}.blackfire.local
          - ${COMPOSE_PROJECT_NAME}.debug.local
          - ${COMPOSE_PROJECT_NAME}.dev.local
          - ${COMPOSE_PROJECT_NAME}.fire.local
          - ${COMPOSE_PROJECT_NAME}.mail.local
          - ${COMPOSE_PROJECT_NAME}.xdbg.local
          - ${COMPOSE_PROJECT_NAME}.xdebug.local
    depends_on:
      - db
      - php
      - php_blackfire
      - php_xdebug

  db:
    image: mariadb:10.1
    env_file:
      - ./.env
    volumes:
      - ${CONFIGURATION_ROOT}/db:/docker-entrypoint-initdb.d/:ro
      - ${CONFIGURATION_ROOT}/db/mysql.cnf:/etc/mysql/conf.d/zzz-custom.cnf:ro
      - dbRamdisk:/var/lib/mysql

  php:
    build: ${CONFIGURATION_ROOT}/php/
    volumes:
      - ${CONFIGURATION_ROOT}/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ${CONFIGURATION_ROOT}/php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ${PROJECT_ROOT}:/var/www/html
      - typo3tempRamdisk:/var/www/html/Web/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - before_script

  php_blackfire:
    build: ${CONFIGURATION_ROOT}/php_blackfire/
    volumes:
      - ${CONFIGURATION_ROOT}/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ${CONFIGURATION_ROOT}/php_blackfire/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ${PROJECT_ROOT}:/var/www/html
      - typo3tempRamdisk:/var/www/html/Web/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - before_script

  php_xdebug:
    build: ${CONFIGURATION_ROOT}/php_xdebug/
    volumes:
      - ${CONFIGURATION_ROOT}/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ${CONFIGURATION_ROOT}/php_xdebug/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ${PROJECT_ROOT}:/var/www/html
      - typo3tempRamdisk:/var/www/html/Web/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - before_script

  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID:-id}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN:-token}
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID:-id}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN:-token}
    depends_on:
      - php_blackfire
      - web

  before_script:
    image: busybox:latest
    volumes:
      - ${PROJECT_ROOT}:/build
      - ${CONFIGURATION_ROOT}:/configuration
    entrypoint: /configuration/template/${TEMPLATE:-default}/init.sh

  mailhog:
    image: mailhog/mailhog
    hostname: ${COMPOSE_PROJECT_NAME}.mailhog.local

  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH:-nan}
      - NGROK_PORT=${NGROK_PORT:-nan}
      - NGROK_REGION=${NGROK_REGION:-eu}
      - NGROK_BINDTLS=${NGROK_BINDTLS:-true}
      - NGROK_USERNAME=${NGROK_USERNAME:-nan}
      - NGROK_PASSWORD=${NGROK_PASSWORD:-nan}
    depends_on:
      - web

  hostmap:
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/hosts:/tmp/hosts

volumes:
  dbRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: noatime,noexec,nodiratime,nodev,nosuid,async,mode=0777
  typo3tempRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: noatime,noexec,nodiratime,nodev,nosuid,async,mode=0777
  typo3varRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: noatime,noexec,nodiratime,nodev,nosuid,async,mode=0777
