version: "3"
services:
  web:
    build:
      context: ./web
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        TYPO3_CONTEXT: ${TYPO3_CONTEXT}
    container_name: ${COMPOSE_PROJECT_NAME}_web
    hostname: ${COMPOSE_PROJECT_NAME}.dev.local
    volumes:
      - ${HOSTS_FILE:-/etc/hosts}:/etc/hosts:ro
      - ./web/ssl:/etc/nginx/ssl:ro
      - $PWD:/var/www/html:ro
    networks:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.bf.local
          - ${COMPOSE_PROJECT_NAME}.black.local
          - ${COMPOSE_PROJECT_NAME}.blackfire.local
          - ${COMPOSE_PROJECT_NAME}.debug.local
          - ${COMPOSE_PROJECT_NAME}.fire.local
          - ${COMPOSE_PROJECT_NAME}.logs.local
          - ${COMPOSE_PROJECT_NAME}.mail.local
          - ${COMPOSE_PROJECT_NAME}.xdbg.local
          - ${COMPOSE_PROJECT_NAME}.xdebug.local
    depends_on:
      - before_script
      - db
      - php
      - php_blackfire
      - php_xdebug
      - mail

  db:
    image: mariadb:${DATABASE_VERSION:-11.2}
    hostname: ${COMPOSE_PROJECT_NAME}_db
    container_name: ${COMPOSE_PROJECT_NAME}_db
    env_file:
      - $PWD/.env
    volumes:
      - dbData:/var/lib/mysql
      - ./db/mariadb.cnf:/etc/mysql/conf.d/zz-my-mariadb.cnf:ro
      - ./db/mariadb.cnf:/etc/mysql/mysql.d/zz-my-mariadb.cnf:ro
      - ./db/import:/docker-entrypoint-initdb.d/:ro
    depends_on:
      - before_script

  php:
    image: tuurlijk/php-fpm:${PHP_VERSION:-8.2}
    hostname: ${COMPOSE_PROJECT_NAME}_php
    container_name: ${COMPOSE_PROJECT_NAME}_php
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
    volumes:
      - $PWD/:/var/www/html/
      - ${HOSTS_FILE:-/etc/hosts}:/etc/hosts:ro
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ${HOME:-~}/.composer:/home/dev/.composer
      - ${HOME:-~}/.composer:/home/docker/.composer
    depends_on:
      - before_script

  php_blackfire:
    image: tuurlijk/php-fpm:${PHP_VERSION:-8.2}-blackfire
    hostname: ${COMPOSE_PROJECT_NAME}_php_blackfire
    container_name: ${COMPOSE_PROJECT_NAME}_php_blackfire
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
    volumes:
      - $PWD/:/var/www/html/
      - ${HOSTS_FILE:-/etc/hosts}:/etc/hosts:ro
      - ./php_blackfire/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
    depends_on:
      - before_script

  php_xdebug:
    image: tuurlijk/php-fpm:${PHP_VERSION:-8.2}-xdebug
    hostname: ${COMPOSE_PROJECT_NAME}_php_xdebug
    container_name: ${COMPOSE_PROJECT_NAME}_php_xdebug
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
      - PHP_IDE_CONFIG=serverName=${COMPOSE_PROJECT_NAME}
    volumes:
      - $PWD/:/var/www/html/
      - ./php_xdebug/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
    depends_on:
      - before_script
    extra_hosts:
      - "host.docker.internal:host-gateway"

  blackfire:
    image: blackfire/blackfire
    container_name: ${COMPOSE_PROJECT_NAME}_blackfire
    environment:
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID:-id}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN:-token}
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID:-id}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN:-token}
    depends_on:
      - php_blackfire
      - web

  before_script:
    user: "${UID:-1000}:${GID:-1000}"
    image: bash
    container_name: ${COMPOSE_PROJECT_NAME}_before_script
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
    volumes:
      - $PWD:/build
      - ./:/configuration
    entrypoint: /configuration/template/${TEMPLATE:-default}/before.sh
    depends_on:
      - before

  after_script:
    user: "${UID:-1000}:${GID:-1000}"
    image: tuurlijk/php-fpm:${PHP_VERSION:-8.2}
    container_name: ${COMPOSE_PROJECT_NAME}_after_script
    env_file:
      - $PWD/.env
    volumes:
      - ./:/configuration
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - $PWD/.docker/db/mysql:/var/lib/mysql
      - $PWD:/var/www/html
      - ${HOME:-~}/.composer:/home/dev/.composer
      - ${HOME:-~}/.composer:/home/docker/.composer
    depends_on:
      - web
    entrypoint: /configuration/template/${TEMPLATE:-default}/after.sh

  mail:
    image: axllent/mailpit
    container_name: ${COMPOSE_PROJECT_NAME}_mail
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - before_script

  hosts:
    image: ${HOSTS_IMAGE:-dvdarias/docker-hoster}
    container_name: ${COMPOSE_PROJECT_NAME}_hosts
    volumes:
      - //var/run/docker.sock:/tmp/docker.sock:ro
      - ${HOSTS_FILE:-/etc/hosts}:/tmp/hosts

  logs:
    image: amir20/dozzle
    container_name: ${COMPOSE_PROJECT_NAME}_logs
    environment:
      - DOZZLE_FILTER=name=${COMPOSE_PROJECT_NAME}_(web|php*|db|mail*|solr|redis)_*
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock:ro

  before:
    user: "${UID:-1000}:${GID:-1000}"
    image: bash
    container_name: ${COMPOSE_PROJECT_NAME}_before
    env_file:
      - $PWD/.env
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/Developer}
    volumes:
      - $PWD/:/build
      - ./:/configuration
    entrypoint: /configuration/before/before.sh

volumes:
  dbData:
    driver: local
