version: "3"
services:
  web:
    image: fholzer/nginx-brotli
    hostname: ${COMPOSE_PROJECT_NAME}.dev.local
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/ssl:/etc/nginx/ssl:ro
      - ../:/var/www/html:ro
      - typo3tempRamdisk:/var/www/html/Web/typo3temp:ro
      - typo3varRamdisk:/var/www/html/var:ro
    networks:
      default:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.bf.local
          - ${COMPOSE_PROJECT_NAME}.black.local
          - ${COMPOSE_PROJECT_NAME}.blackfire.local
          - ${COMPOSE_PROJECT_NAME}.debug.local
          - ${COMPOSE_PROJECT_NAME}.fire.local
          - ${COMPOSE_PROJECT_NAME}.mail.local
          - ${COMPOSE_PROJECT_NAME}.xdbg.local
          - ${COMPOSE_PROJECT_NAME}.xdebug.local
    depends_on:
      - db
      - php
      - php_blackfire
      - php_xdebug

  db:
    image: mariadb:latest
    env_file:
      - ../.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./db/mysql.cnf:/etc/mysql/conf.d/zzz-custom.cnf:ro
      - ./db/mysql.cnf:/etc/mysql/mariadb.conf.d/zzz-custom.cnf:ro
      - dbRamdisk:/var/lib/mysql

  php:
    user: "${UID:-1000}:${GID:-1000}"
    build: ./php
    volumes:
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ../:/var/www/html
      - typo3tempRamdisk:/var/www/html/Web/typo3temp
      - typo3varRamdisk:/var/www/html/var
      - ${HOME:-~}/.composer:/home/dev/.composer
      - ${HOME:-~}/.composer:/home/docker/.composer
    depends_on:
      - before_script

  php_blackfire:
    user: "${UID:-1000}:${GID:-1000}"
    build: ./php_blackfire
    volumes:
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ./php_blackfire/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ../:/var/www/html
      - typo3tempRamdisk:/var/www/html/Web/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - before_script

  php_xdebug:
    user: "${UID:-1000}:${GID:-1000}"
    build: ./php_xdebug
    volumes:
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-custom-fpm.conf:ro
      - ./php_xdebug/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ../:/var/www/html
      - typo3tempRamdisk:/var/www/html/Web/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - before_script

  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID:-id}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN:-token}
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID:-id}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN:-token}
    depends_on:
      - php_blackfire
      - web

  before_script:
    user: "${UID:-1000}:${GID:-1000}"
    image: bash:latest
    env_file:
      - ../.env
    volumes:
      - ../:/build
      - ./:/configuration
    entrypoint: /configuration/template/${TEMPLATE:-default}/before.sh

  after_script:
    user: "${UID:-1000}:${GID:-1000}"
    build: ./php
    env_file:
      - ../.env
    volumes:
      - ./:/configuration
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - ../:/var/www/html
      - ${HOME:-~}/.composer:/home/dev/.composer
      - ${HOME:-~}/.composer:/home/docker/.composer
      - typo3tempRamdisk:/var/www/html/Web/typo3temp
      - typo3varRamdisk:/var/www/html/var
    depends_on:
      - web
    entrypoint: /configuration/template/${TEMPLATE:-default}/after.sh

  mailhog:
    image: mailhog/mailhog
    hostname: ${COMPOSE_PROJECT_NAME}.mailhog.local

  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH:-nan}
      - NGROK_PORT=${NGROK_PORT:-nan}
      - NGROK_REGION=${NGROK_REGION:-eu}
      - NGROK_BINDTLS=${NGROK_BINDTLS:-true}
      - NGROK_USERNAME=${NGROK_USERNAME:-nan}
      - NGROK_PASSWORD=${NGROK_PASSWORD:-}
    depends_on:
      - web

  hostmap:
    image: dvdarias/docker-hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/hosts:/tmp/hosts

#  redis:
#    image: redis:latest

volumes:
  dbRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "noatime,noexec,nodiratime,nodev,nosuid,async,mode=0770,uid=${UID:-1000},gid=${GID:-1000}"
  typo3tempRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "noatime,noexec,nodiratime,nodev,nosuid,async,mode=0770,uid=${UID:-1000},gid=${GID:-1000}"
  typo3varRamdisk:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "noatime,noexec,nodiratime,nodev,nosuid,async,mode=0770,uid=${UID:-1000},gid=${GID:-1000}"
